-- 제품을 구매를 취소했을 때 트리거
use shoppingmall;

DROP TRIGGER IF EXISTS UPDATE_BUY;

DELIMITER //
CREATE TRIGGER UPDATE_BUY AFTER UPDATE
ON BUY  
FOR EACH ROW
BEGIN
-- 제품 수량을 변경
IF NEW.BUY_AMOUNT = OLD.BUY_AMOUNT AND NEW.BUY_STATUS = '구매취소' THEN
	UPDATE PRODUCT 
		SET PR_AMOUNT = PR_AMOUNT + OLD.BUY_AMOUNT -- NEW,OLD 둘중 암거나 써도 상관없는 상황 => 구매제품 기본키가 안바뀌기 떄문에,,
	WHERE PR_NUM = NEW.BUY_PR_NUM;
ELSE 
    IF NEW.BUY_AMOUNT != OLD.BUY_AMOUNT THEN
    UPDATE PRODUCT 
		SET PR_AMOUNT = PR_AMOUNT + OLD.BUY_AMOUNT - NEW.BUY_AMOUNT
	WHERE PR_NUM = OLD.BUY_PR_NUM;
	END IF;
END IF;
END //
DELIMITER ;

UPDATE BUY SET BUY_STATUS = '구매취소' WHERE BUY_NUM ='abc1';

