-- 2022년 1학기 컴퓨터 개론을 수강하는 학생들 명단을 조회
SELECT  DISTINCT ST_NAME FROM STUDENT 
JOIN COURSE ON ST_NUM = CO_ST_NUM
JOIN LECTURE ON LE_NUM = CO_LE_NUM 
WHERE LE_NAME LIKE '컴퓨터 개론' AND LE_TERM = 1 AND LE_YEAR LIKE 2022;

-- 2022년 1학기에 2022160001 학생이 수강한 과목명을 조회
SELECT DISTINCT LE_NAME AS 과목명 FROM STUDENT 
JOIN COURSE ON ST_NUM = CO_ST_NUM
JOIN LECTURE ON LE_NUM = CO_LE_NUM 
WHERE LE_YEAR LIKE 2022 AND LE_TERM = 1 AND ST_NUM LIKE '2022160001';
